name: "Merge Anchor Upstream"
description: "Merge Anchor Upstream"

inputs:
  repo-token:
    description: "Token with permissions to do repo things"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        ref: master # set the branch to merge to
        fetch-depth: 0
    - run: git config --global user.email "Elias.cmoreno17@gmail.com"
      shell: bash
    - run: git config --global user.name "Eliascm17"
      shell: bash
    - run: git remote add upstream https://github.com/project-serum/anchor.git
      shell: bash
    - run: git pull upstream master --no-ff
      shell: bash
    - run: git push origin master
      shell: bash

    #     - name: Update Anchor toml files to latest solana release
    # get-version:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - name: Get Latest Tag
    #       run:
    #         mkdir .github/releases | curl -sL https://api.github.com/repos/solana-labs/solana/releases/latest | \
    #         jq -r ".tag_name" > .github/releases/solana-latest.txt
    #     - name: Checkout new branch for latest tag

    #     - name: Update toml files to solana latest release
    #       run: ../../../update.sh
    #       shell: bash

    #     - name: Create and merge pull request with updated dependencies
