name: Merge Upstream

on:
  push:
    branches:
      - master
jobs:
  merge-upstream:
    name: Merge Upstream
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/merge-upstream/
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
